// <auto-generated />
namespace Globaltek_Market.Infraestructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitCrear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitCrear));
        
        string IMigrationMetadata.Id
        {
            get { return "202310041728539_InitCrear"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
